/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.0-rc-3/samples
 */
plugins {
    java

    id("me.champeau.jmh") version ("0.7.3")
}

group = "com.priyakdey"
version = "0.0.1"
description = "Playground for the Count Squares algorithm problem."

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    jmh("org.openjdk.jmh:jmh-core:1.37")
    jmh("org.openjdk.jmh:jmh-generator-annprocess:1.37")
}

jmh {
    timeUnit.set("us")
    profilers.add("gc")

    resultFormat.set("JSON")
    resultsFile.set(layout.buildDirectory.file("results/jmh/results.json"))
}
